name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Use the version of Node.js you need

      - name: Install dependencies
        working-directory: ./The-Bus-CardGame
        run: npm install  # Or use 'yarn install' if you use Yarn

      - name: Build
        working-directory: ./The-Bus-CardGame
        run: npm run build  # Or 'yarn build'

      - name: List build directory
        working-directory: ./The-Bus-CardGame
        run: ls -la ./build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./The-Bus-CardGame/build
